

GET https://705z8vffi0.execute-api.us-east-1.amazonaws.com/prod/spaces
###

POST https://705z8vffi0.execute-api.us-east-1.amazonaws.com/prod/spaces
content-type: application/json

{
  "location": "Brasilia, Brasil"
}
###