@url = https://705z8vffi0.execute-api.us-east-1.amazonaws.com/prod/spaces
@token = add-your-token-here

GET {{url}}
Authorization: {{token}}
###

GET {{url}}?id=37472f38-4ff0-4b96-876e-4ae2b46d0d14
###

POST {{url}}
content-type: application/json

{
  "location": "Brasilia, Brasil",
  "name": "Café do Museu",
  "country": "Brasil",
  "photoUrl": "https://"
}
###

DELETE {{url}}?id=37472f38-4ff0-4b96-876e-4ae2b46d0d14
Authorization: {{token}}
###

PUT {{url}}?id=37472f38-4ff0-4b96-876e-4ae2b46d0d14
content-type: application/json

{
  "location": "Sobradinho, Brasil",
  "name": "Museu Nacional",
  "country": "Brasil",
  "photoUrl": "https://"
}
###